// Copyright 2026 The uTLS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license retained at testdata/chrome155/LICENSE.
// Adapted from cppla/utls 7295e1b508c3 u_chrome155_test.go.

package tunnel

import (
	"bytes"
	"context"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"io"
	"net"
	"os"
	"reflect"
	"slices"
	"sort"
	"strings"
	"testing"
	"time"
)

// This parser is deliberately independent of Fingerprinter: comparing the
// captured browser bytes against generated bytes must not hide a parser bug.
// Only extension permutation, GREASE codepoints, ephemeral public keys, and
// GREASE ECH randomness are normalized. Ordered capability lists and trust
// anchor IDs retain their original order and bytes.
type chrome155WireHello struct {
	Version            uint16
	RandomLength       int
	SessionIDLength    int
	CipherSuites       []uint16
	CompressionMethods []byte
	Extensions         map[uint16][]string
	FixedExtensions    []string
}

type chrome155Reader struct {
	t     *testing.T
	b     []byte
	label string
}

func (r *chrome155Reader) take(n int) []byte {
	r.t.Helper()
	if n < 0 || n > len(r.b) {
		r.t.Fatalf("%s: truncated field: need %d bytes, have %d", r.label, n, len(r.b))
	}
	b := r.b[:n]
	r.b = r.b[n:]
	return b
}

func (r *chrome155Reader) number(n int) int {
	r.t.Helper()
	v := 0
	for _, b := range r.take(n) {
		v = v<<8 | int(b)
	}
	return v
}

func (r *chrome155Reader) vector(n int) []byte {
	r.t.Helper()
	return r.take(r.number(n))
}

func (r *chrome155Reader) end() {
	r.t.Helper()
	if len(r.b) != 0 {
		r.t.Fatalf("%s: %d trailing bytes", r.label, len(r.b))
	}
}

func chrome155NormalizeGREASE(v uint16) uint16 {
	if chrome155IsGREASE(v) {
		return 0x0a0a
	}
	return v
}

func chrome155Uint16s(t *testing.T, b []byte) []uint16 {
	t.Helper()
	if len(b)%2 != 0 {
		t.Fatalf("odd uint16 vector length: %d", len(b))
	}
	out := make([]uint16, len(b)/2)
	for i := range out {
		out[i] = chrome155NormalizeGREASE(uint16(b[2*i])<<8 | uint16(b[2*i+1]))
	}
	return out
}

func chrome155NormalizeExtension(t *testing.T, id uint16, body []byte) string {
	t.Helper()
	r := chrome155Reader{t, body, fmt.Sprintf("extension %#04x", id)}
	var value string
	switch id {
	case 10, 13: // supported_groups, signature_algorithms
		value = fmt.Sprint(chrome155Uint16s(t, r.vector(2)))
	case 43: // supported_versions
		value = fmt.Sprint(chrome155Uint16s(t, r.vector(1)))
	case 51: // key_share
		shares := chrome155Reader{t, r.vector(2), "key_share entries"}
		var entries []string
		for len(shares.b) > 0 {
			group := uint16(shares.number(2))
			key := shares.vector(2)
			entry := fmt.Sprintf("%04x/%d", chrome155NormalizeGREASE(group), len(key))
			if chrome155IsGREASE(group) {
				entry += "/" + hex.EncodeToString(key)
			}
			entries = append(entries, entry)
		}
		value = strings.Join(entries, ",")
	case 0xfe0d: // GREASE encrypted_client_hello
		outer, kdf, aead := r.number(1), r.number(2), r.number(2)
		r.take(1) // randomized config_id
		enc, payload := r.vector(2), r.vector(2)
		if outer != 0 || !slices.Contains([]int{144, 176, 208, 240}, len(payload)) {
			t.Fatalf("unexpected GREASE ECH shape: outer=%d, payload length=%d", outer, len(payload))
		}
		value = fmt.Sprintf("%d/%d/%d/enc=%d/payload=144,176,208,240", outer, kdf, aead, len(enc))
	case 0xca34: // trust_anchors
		ids := chrome155Reader{t, r.vector(2), "trust anchor IDs"}
		for len(ids.b) > 0 {
			if len(ids.vector(1)) == 0 {
				t.Fatal("empty trust anchor ID in fixture")
			}
		}
		value = hex.EncodeToString(body)
	default:
		value = hex.EncodeToString(r.take(len(r.b)))
	}
	r.end()
	return value
}

func chrome155ParseWire(t *testing.T, data []byte) (chrome155WireHello, []uint16, map[uint16][]byte) {
	t.Helper()
	r := chrome155Reader{t, data, "ClientHello"}
	if len(data) > 0 && data[0] == byte(22) {
		if r.number(1) != 22 || r.number(2) != 0x0301 {
			t.Fatal("unexpected ClientHello TLS record header")
		}
		record := r.vector(2)
		r.end()
		r = chrome155Reader{t, record, "ClientHello handshake"}
	}
	if r.number(1) != 1 {
		t.Fatal("fixture is not a ClientHello")
	}
	body := r.vector(3)
	r.end()
	r = chrome155Reader{t, body, "ClientHello body"}
	version := uint16(r.number(2))
	random := r.take(32)
	sid := r.vector(1)
	ciphers := chrome155Uint16s(t, r.vector(2))
	compression := bytes.Clone(r.vector(1))
	extensions := r.vector(2)
	r.end()
	out := chrome155WireHello{
		Version: version, RandomLength: len(random), SessionIDLength: len(sid),
		CipherSuites: ciphers, CompressionMethods: compression, Extensions: make(map[uint16][]string),
	}
	r = chrome155Reader{t, extensions, "ClientHello extensions"}
	seen, raw := make(map[uint16]bool), make(map[uint16][]byte)
	var order []uint16
	for len(r.b) > 0 {
		id := uint16(r.number(2))
		body := r.vector(2)
		if seen[id] {
			t.Fatalf("duplicate extension %#04x", id)
		}
		seen[id] = true
		raw[id] = bytes.Clone(body)
		normalizedID := chrome155NormalizeGREASE(id)
		order = append(order, id)
		out.Extensions[normalizedID] = append(out.Extensions[normalizedID], chrome155NormalizeExtension(t, id, body))
	}
	for _, values := range out.Extensions {
		sort.Strings(values) // distinguish the two GREASE bodies independently of their values
	}
	out.FixedExtensions = chrome155PinnedExtensions(order, raw)
	return out, order, raw
}

// Chrome shuffles ordinary extensions, but GREASE, padding and PSK retain
// their positions. Keep the body attached to its position as well as its ID.
func chrome155PinnedExtensions(order []uint16, raw map[uint16][]byte) []string {
	var fixed []string
	for position, id := range order {
		if chrome155IsGREASE(id) || id == 21 || id == 41 {
			fixed = append(fixed, fmt.Sprintf("%d/%04x/%x", position, chrome155NormalizeGREASE(id), raw[id]))
		}
	}
	return fixed
}

func chrome155Fixture(t *testing.T) []byte {
	t.Helper()
	text, err := os.ReadFile("testdata/chrome155/clienthello.hex")
	if err != nil {
		t.Fatal(err)
	}
	data, err := hex.DecodeString(strings.Join(strings.Fields(string(text)), ""))
	if err != nil {
		t.Fatal(err)
	}
	if len(data) != 1955 || fmt.Sprintf("%x", sha256.Sum256(data[5:])) != "235618e3922e52a71a9f6593a71ec4ca182dab6b3ab4e90a2a1733133e97439a" {
		t.Fatal("browser fixture size or SHA-256 changed; audit provenance before updating")
	}
	return data
}

func chrome155FixtureServerName(t *testing.T, raw map[uint16][]byte) string {
	t.Helper()
	r := chrome155Reader{t, raw[0], "server_name"}
	names := chrome155Reader{t, r.vector(2), "server_name list"}
	r.end()
	if names.number(1) != 0 {
		t.Fatal("fixture SNI is not a host name")
	}
	name := string(names.vector(2))
	names.end()
	return name
}

func chrome155IsGREASE(v uint16) bool {
	return byte(v>>8) == byte(v) && v&0x0f0f == 0x0a0a
}

// Capture the application's real connection wrapper writing bytes to a peer,
// not a preset or a Fingerprinter round-trip. No public network is contacted.
func captureChrome155Wire(t *testing.T, profile FingerprintProfile, config *tls.Config) []byte {
	t.Helper()
	client, peer := net.Pipe()
	defer client.Close()
	defer peer.Close()
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	deadline, _ := ctx.Deadline()
	if err := peer.SetDeadline(deadline); err != nil {
		t.Fatal(err)
	}
	conn, err := newWebH2TLSClientConn(client, config, profile, newWebH2UTLSSessionCache(config))
	if err != nil {
		t.Fatal(err)
	}
	done := make(chan error, 1)
	go func() { done <- conn.HandshakeContext(ctx) }()
	// Always join the handshake goroutine, including on a failed read.
	defer func() {
		peer.Close()
		if err := <-done; err == nil {
			t.Error("capture-only peer unexpectedly completed a TLS handshake")
		}
	}()
	var header [5]byte
	if _, err := io.ReadFull(peer, header[:]); err != nil {
		t.Fatal(err)
	}
	body := make([]byte, int(binary.BigEndian.Uint16(header[3:])))
	if _, err := io.ReadFull(peer, body); err != nil {
		t.Fatal(err)
	}
	return append(header[:], body...)
}

func TestChrome155ActualClientHelloMatchesBrowserFixture(t *testing.T) {
	want, _, raw := chrome155ParseWire(t, chrome155Fixture(t))
	for _, policy := range []string{"empty-cache", "nil-cache", "tickets-disabled"} {
		t.Run(policy, func(t *testing.T) {
			config := &tls.Config{
				ServerName:         chrome155FixtureServerName(t, raw),
				RootCAs:            x509.NewCertPool(),
				ClientSessionCache: tls.NewLRUClientSessionCache(8),
			}
			if policy == "nil-cache" {
				config.ClientSessionCache = nil
			}
			config.SessionTicketsDisabled = policy == "tickets-disabled"
			// Exercise independent GREASE, ECH randomness and shuffled extensions.
			for sample := 0; sample < 8; sample++ {
				got, _, emitted := chrome155ParseWire(t, captureChrome155Wire(t, FingerprintChrome155, config))
				if !reflect.DeepEqual(got, want) {
					t.Fatalf("sample %d differs from captured Chrome 155:\n got: %+v\nwant: %+v", sample, got, want)
				}
				if ticket, ok := emitted[35]; !ok || len(ticket) != 0 {
					t.Fatal("cold ClientHello must contain an empty session_ticket")
				}
				for _, forbidden := range []uint16{41, 42} {
					if _, ok := emitted[forbidden]; ok {
						t.Fatalf("cold ClientHello must not contain extension %d (PSK/early_data)", forbidden)
					}
				}
			}
		})
	}
}

func TestChrome155ComparisonPreservesCapabilityDifferences(t *testing.T) {
	want, order, raw := chrome155ParseWire(t, chrome155Fixture(t))
	if len(want.FixedExtensions) != 2 || !chrome155IsGREASE(order[0]) || !chrome155IsGREASE(order[len(order)-1]) || len(raw[order[0]]) != 0 || !bytes.Equal(raw[order[len(order)-1]], []byte{0}) {
		t.Fatal("expected fixed leading empty GREASE and trailing one-byte GREASE")
	}
	shuffled := slices.Clone(order)
	shuffled[1], shuffled[2] = shuffled[2], shuffled[1]
	if !reflect.DeepEqual(chrome155PinnedExtensions(shuffled, raw), want.FixedExtensions) {
		t.Fatal("ordinary extension permutation should remain allowed")
	}
	shuffled[0], shuffled[1] = shuffled[1], shuffled[0]
	if reflect.DeepEqual(chrome155PinnedExtensions(shuffled, raw), want.FixedExtensions) {
		t.Fatal("comparison hid a displaced GREASE extension")
	}
	swappedBodies := make(map[uint16][]byte, len(raw))
	for id, body := range raw {
		swappedBodies[id] = body
	}
	swappedBodies[order[0]], swappedBodies[order[len(order)-1]] = raw[order[len(order)-1]], raw[order[0]]
	if reflect.DeepEqual(chrome155PinnedExtensions(order, swappedBodies), want.FixedExtensions) {
		t.Fatal("comparison hid swapped positional GREASE bodies")
	}
	legacy, _, legacyRaw := chrome155ParseWire(t, captureChrome155Wire(t, FingerprintChrome133, &tls.Config{
		ServerName: chrome155FixtureServerName(t, raw),
		RootCAs:    x509.NewCertPool(),
	}))
	if reflect.DeepEqual(legacy, want) {
		t.Fatal("normalization hid the Chrome 133/155 capability difference")
	}
	if _, ok := legacyRaw[0xca34]; ok {
		t.Fatal("Chrome 155 trust anchors leaked into the immutable Chrome 133 profile")
	}
	if reflect.DeepEqual(legacy.Extensions[13], want.Extensions[13]) {
		t.Fatal("comparison hid different signature algorithm lists")
	}
	// No normalization is permitted for the advertised trust-anchor IDs.
	changed := bytes.Clone(raw[0xca34])
	changed[len(changed)-1] ^= 1
	if chrome155NormalizeExtension(t, 0xca34, changed) == chrome155NormalizeExtension(t, 0xca34, raw[0xca34]) {
		t.Fatal("comparison hid a changed trust anchor")
	}
	// Ordered capabilities stay ordered, even when GREASE values are ignored.
	signatures := bytes.Clone(raw[13])
	copy(signatures[4:6], raw[13][6:8])
	copy(signatures[6:8], raw[13][4:6])
	if chrome155NormalizeExtension(t, 13, signatures) == chrome155NormalizeExtension(t, 13, raw[13]) {
		t.Fatal("comparison hid reordered signature schemes")
	}
	if chrome155IsGREASE(0x1a2a) || !chrome155IsGREASE(0x1a1a) {
		t.Fatal("GREASE normalization must not mask non-GREASE values")
	}
}
